---
title: "Covid cases in Manitoba"
output: html_notebook
---

Libraries
```{r}
library(tidyverse)
library(here)
```

Read in data
```{r}
df <- read_csv(here("data", "MB_data.csv"))
df
df$CumulHosp <- cumsum(df$NewHosp)
```

Plot cumulative cases
```{r}
gCC <- ggplot(df, aes(x = CumulDate)) +
  geom_point(aes(y = Cases, colour = "Cases")) +
  geom_line(aes(y = Cases, colour = "Cases")) +
  geom_point(aes(y = CumulHosp*10, colour = "Hospitalizations")) +
  geom_line(aes(y = CumulHosp*10, colour = "Hospitalizations")) +
  scale_y_continuous(breaks = seq(0, 200, by = 25), sec.axis = sec_axis(~ . / 10, name = "Cumulative hospitalizations")) +
  theme_bw() +
  scale_colour_manual(values = c("blue", "red")) +
  labs(x = "Days since first cases (March 12)", y ="Cumulative cases", caption ="Data source: Government of Manitoba\n Code: github.com/acgerstein/COVID19-MB", title = "Manitoba COVID-19 data (as of April 2, 2020", colour = "") +
  theme(legend.position = c(0.25, 0.85), plot.title = element_text(hjust = 0, vjust=2.12))

gCC
```

Save
```{r}
ggsave(filename = here("figures", "0402_MB.png"), plot = gCC, device = "png", height = 10, width = 10, units = "cm")
```
